apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-config
  namespace: zchannel
data:
  custom: |
    server {
    server_name zchannel.yourdomain.com;
    listen 80;






    location / {



        client_max_body_size "50m";


        proxy_set_header Host                   $host;

        # Pass Real IP
        proxy_set_header X-Real-IP              $remote_addr;

        # Allow websocket connections
        proxy_set_header                        Upgrade           $http_upgrade;
        proxy_set_header                        Connection        $connection_upgrade;

        proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host       $host;
        proxy_set_header X-Forwarded-Port       $server_port;
        proxy_set_header X-Forwarded-Proto      $pass_access_scheme;

        proxy_connect_timeout                   5s;
        proxy_send_timeout                      60s;
        proxy_read_timeout                      60s;

        proxy_redirect                          off;
        proxy_buffering                         off;

        proxy_http_version                      1.1;


        proxy_pass http://zchannel-php-zchannel-80;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: py-ingress-config
  namespace: zchannel
data:
  custom: |
    server {
        server_name zchannel.yourdomain.mz;
        listen 80;






        location / {


        client_max_body_size "50m";




                proxy_set_header Host                   $host;

                # Pass Real IP
                proxy_set_header X-Real-IP              $remote_addr;

                # Allow websocket connections
                proxy_set_header                        Upgrade           $http_upgrade;
                proxy_set_header                        Connection        $connection_upgrade;

                proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host       $host;
                proxy_set_header X-Forwarded-Port       $server_port;
                proxy_set_header X-Forwarded-Proto      $pass_access_scheme;

                proxy_connect_timeout                   5s;
                proxy_send_timeout                      60s;
                proxy_read_timeout                      60s;

                proxy_redirect                          off;
                proxy_buffering                         off;

                proxy_http_version                      1.1;


                proxy_pass http://zchannel-py-zchannel-8005;
        }
    }
